name: Build and Publish pyjpt to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version triple, such as x.y.z'

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  cancel:
    name: Cancel Previous Runs ⛔
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action
      - uses: styfle/cancel-workflow-action
        with:
          workflow_id: reusable-test-and-build.yml

  build-and-test:
    name: Run the test suite on the latest checkout
    uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-test-and-build.yml@main'
    needs: cancel
    with:
      version: ${{ github.ref || inputs.version }}
      python-versions: "cp38-cp38"

  publish:
    name: Run the test suite on the latest checkout
    uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-publish-package.yml@main'
    needs: build-and-test
    secrets: inherit
