name: Publish the pyjpt package to PyPI and TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version triple, such as x.y.z'

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
    build-and-test:
      name: Run the test suite on the latest checkout
      uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-test-and-build.yml@main'
      with:
        version: ${{ github.ref }}

    publish:
      name: Run the test suite on the latest checkout
      uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-publish-package.yml@main'
      needs: build-and-test