name: Publish the pyjpt package to PyPI and TestPyPI

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
    build-and-publish:
      name: Publish Python distribution to the Python package index
      runs-on: ubuntu-22.04

      steps:
          - name: Test and Build pyjpt Version for target ${{ github.ref }} 📦
            uses: joint-probability-trees/jpt-dev/.github/workflows/test-and-build.yml@master
            with:
              version: ${{ github.ref }}

          - name: Publish distribution to Test PyPI 📢
            uses: pypa/gh-action-pypi-publish@master
            with:
                password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                skip_existing: true
                repository_url: https://test.pypi.org/legacy/
                
          - name: Install wheel from Test PyPI 🛞
            run: >- 
              python -m pip install -i https://test.pypi.org/simple/ pyjpt
            
          - name: Check the installation from Test PyPI ✅
            run: >-
              python -c "import jpt"

          - name: Publish distribution Version ${{ github.ref }} to PyPI 🏁
            uses: pypa/gh-action-pypi-publish@master
            with:
              password: ${{ secrets.PYPI_API_TOKEN }}
              skip_existing: false
