name: Build and Publish pyjpt to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version triple, such as x.y.z'

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

# ----------------------------------------------------------------------------------------------------------------------

concurrency:
  group: 'jpt-testing-and-deployment'
  cancel-in-progress: true

# ----------------------------------------------------------------------------------------------------------------------

jobs:

  build-and-test:
    name: '[${{ github.ref || inputs.version }}] Run the test suite on the latest checkout'
    uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-test-and-build.yml@main'
    needs: cancel
    with:
      version: ${{ github.ref || inputs.version }}
      python-versions: "cp38-cp38"

  # --------------------------------------------------------------------------------------------------------------------

  publish:
    name: '[${{ github.ref || inputs.version }}] Run the test suite on the latest checkout'
    uses: 'joint-probability-trees/jpt-dev/.github/workflows/reusable-publish-package.yml@main'
    needs: build-and-test
    secrets: inherit
