name: (Reausable) Upload Wheel to Test-PyPI and PyPI and test installation

# ----------------------------------------------------------------------------------------------------------------------

on:
  workflow_call:

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

# ----------------------------------------------------------------------------------------------------------------------

jobs:
  publish-wheel:
    name: Publish Python distribution to the Python package index
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------------------------------------------------------------------------
      - name: Get wheel artifacts 📥
        uses: actions/download-artifact@v3
        with:
          name: pyjpt-wheel
          path: dist/

      # ----------------------------------------------------------------------------------------------------------------

      - name: Get pip bootstrap installation 🥾
        uses: wei/wget@v1
        with:
          args: https://bootstrap.pypa.io/get-pip.py

      - name: Install Python & pip 💽
        run: |
          sudo apt install python3 python-is-python3
          sudo python get-pip.py

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup Graphviz 📊
        uses: ts-graphviz/setup-graphviz@v1

      # ----------------------------------------------------------------------------------------------------------------

      - name: Publish distribution to Test PyPI 📢
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip_existing: false
          repository_url: https://test.pypi.org/legacy/

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install wheel from Test PyPI 🛞
        run: >-
          python -m pip install --extra-index-url https://test.pypi.org/simple/ pyjpt

      # ----------------------------------------------------------------------------------------------------------------

      - name: Check the installation from Test PyPI ✅
        run: >-
          python -c "import jpt; print(jpt.__version__)"

      # ----------------------------------------------------------------------------------------------------------------

      - name: Publish distribution Version ${{ github.ref }} to PyPI 🏁
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: false
