name: Run tests and build the Python distribution

on:
  push:
    branches:
      - main

  # --------------------------------------------------------------------------------------------------------------------

  workflow_call:
    inputs:
      version:
        required: true
        type: string

      python-versions:
        required: true
        type: string
        default: "cp312-cp312"

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

# ----------------------------------------------------------------------------------------------------------------------

concurrency:
  group: 'jpt-building-and-deployment'
  cancel-in-progress: true

# ----------------------------------------------------------------------------------------------------------------------

jobs:
  test-and-build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-latest

    steps:

      - name: Checkout 🛎
        uses: actions/checkout@v3

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
            python-version: 3.12
            cache: pip

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup Graphviz 📊
        uses: ts-graphviz/setup-graphviz@v1

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install user dependencies 🍼
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install developer dependencies 📐
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements-dev.txt"

      # ----------------------------------------------------------------------------------------------------------------

      - name: "Create .version file if necessary [Version # passed is '${{ inputs.version }}'] 🔢"
        if: ${{ inputs.version != '' }}
        run: |
          echo "${{ inputs.version }}" > src/jpt/.version

      # ----------------------------------------------------------------------------------------------------------------

      - name: Run Tests 🎓
        run: |
          cd test
          PYTHONPATH=../src python -m unittest discover

      # ----------------------------------------------------------------------------------------------------------------

      - name: Build binary wheels 🔨
        uses: RalfG/python-wheels-manylinux-build@v0.7.1
        with:
          python-versions: ${{ inputs.python-versions || 'cp312-cp312' }}
          build-requirements: 'numpy cython<3.0.3'
          pip-wheel-args: '-w ./dist-raw --no-deps'

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install Sphinx dependencies 📚
        uses: py-actions/py-dependency-install@v4
        with:
          path: "doc/requirements.txt"

      # ----------------------------------------------------------------------------------------------------------------

      - name: Build Sphinx documentation 📝
        working-directory: ./doc
        run: |
          sudo apt install pandoc
          make html

      # ----------------------------------------------------------------------------------------------------------------

      - name: Make wheel available  🔧
        id: wheel_url
        uses: actions/upload-artifact@v4
        with:
          name: pyjpt-wheel
          path: dist-raw/*manylinux*.whl
